contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #proteinfamilies channel"
    url: https://nfcore.slack.com/channels/proteinfamilies
    about: Discussion about the nf-core/proteinfamilies pipeline
